language: php

php:
  - 5.4
  - 5.5
  - 5.6

script: phpunit  --coverage-clover build/logs/clover.xml

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

after_script:
  - CODECLIMATE_REPO_TOKEN=8b7ee9f9da07b2a4967bcdd0bc1e997ba3ba6335a4541456d0f92db6c215f593 vendor/bin/test-reporter
