language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

addons:
    code_climate:
        repo_token: 961fe75a0544da3bc195fa128e7e2aefe0d058b127bc87ab5da8e5630922a7ab

script: phpunit
